FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

ENV NODE_ENV=production
CMD ["node", "dist/workers/email.worker.js"]
